"""Initial Migration

Revision ID: bcf52e0f5fe0
Revises: 
Create Date: 2025-12-04 16:52:05.878772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bcf52e0f5fe0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_type_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_type_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_type_id'), 'service_type', ['id'], unique=False)
    op.create_index(
        op.f('ix_service_type_service_type_name'),
        'service_type',
        ['service_type_name'],
        unique=True
        )


    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_number', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)


    op.create_table('service',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('service_type_id', sa.Uuid(), nullable=False),
    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('service_contact_number', sa.Integer(), nullable=True),
    sa.Column('service_latitude', sa.Float(), nullable=False),
    sa.Column('service_longitude', sa.Float(), nullable=False),
    sa.Column('service_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('servcice_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('service_age', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    op.create_index(op.f('ix_service_service_name'), 'service', ['service_name'], unique=True)


    op.create_table('user_booked_service',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('serice_status', 
              sa.Enum(
                  'Booked', 'Accepted', 'Rejected', 'Inprogress', 'Completed', 
                  name='servicestatustype'
                  ), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_booked_service_id'), 'user_booked_service', ['id'], unique=False)


    op.create_table('user_service_report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('report_file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_service_report_id'), 'user_service_report', ['id'], unique=False)


    op.create_table('user_booked_service_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_booked_service_id', sa.Uuid(), nullable=False),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_booked_service_id'], ['user_booked_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f(
            'ix_user_booked_service_feedback_id'), 'user_booked_service_feedback', ['id'],
            unique=False
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_user_booked_service_feedback_id'), table_name='user_booked_service_feedback'
        )
    op.drop_table('user_booked_service_feedback')
    op.drop_index(op.f('ix_user_service_report_id'), table_name='user_service_report')
    op.drop_table('user_service_report')
    op.drop_index(op.f('ix_user_booked_service_id'), table_name='user_booked_service')
    op.drop_table('user_booked_service')
    op.drop_index(op.f('ix_service_service_name'), table_name='service')
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_service_type_service_type_name'), table_name='service_type')
    op.drop_index(op.f('ix_service_type_id'), table_name='service_type')
    op.drop_table('service_type')
    op.execute("DROP TYPE servicestatustype;")
    # ### end Alembic commands ###
